name: "gbraad's machinekey Action"
description: 'Write machinekey on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
runs:
  using: 'composite'
  steps:
    - name: Write machine key to file
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.SSH_MACHINE_PRIVATE }}" > ~/.ssh/id_machine
        chmod 600 ~/.ssh/id_machine
        printf "%s\n" "${{ secrets.SSH_MACHINE_PUBLIC }}"  > ~/.ssh/id_machine.pub
      shell: bash
